---
- hosts: all
  user: centos
  become: yes
  become_method: sudo

  tasks:
  - name: Install prerequisites
    package:
      name:
      - vim
      - wget
      - git
      state: present

  - name: Pull Repo
    git:
      repo: "{{ petclinic_repo }}"
      version: "{{ petclinic_branch }}"
      dest: /var/www/spring-petclinic/

  - name: Install Java
    yum:
      name: "java-1.8.0-openjdk"
      state: latest
    become: true

  - name: Install Maven
    yum:
      name: maven
      state: latest
    become: true

  - name: Start Maven
    shell: "./mvnw package /var/www/spring-petclinc/ &"

  - name: Start Java
    shell: "nohup java -jar spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar /var/www/spring-petclinc/target &"
