---
- hosts: all

  tasks:
    - name: "Starting Spring-Petclinic"
      args:
        chdir: /var/www/spring-petclinic/
      shell: "./mvnw package"
      
      
    - name: "Starting Spring-Petclinic Java"
      args:
        chdir: /var/www/spring-petclinic/
      shell: "nohup java -jar target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar &"
